---
# handlers file for ansible-rabbitmq
- name: restart rabbitmq-server
  service:
    name: "rabbitmq-server"
    state: restarted
  become: true

- name: mark clustering
  file:
    path: /etc/rabbitmq/clustered
    state: touch
  become: true
